### ISSUE TITLE
Email format validator has false negatives on funky domain extensions

### ISSUE THREAD

**Issue by green-coder** [open-company/open-company-web#846]
My email address was reported as incorrect because it finishes by `.taipei`.

`.tw` works, so I guess that there is a whitelist somewhere that may need an update - or maybe there shouldn't be a whitelist.

I spotted the problem in 2 places:

![email-format-problem](https://user-images.githubusercontent.com/598193/56588262-957f3900-6615-11e9-82e9-45b66c3aa045.png)

![image](https://user-images.githubusercontent.com/598193/56589052-18ed5a00-6617-11e9-8796-6bbf61ee29c0.png)

However, the validation problem did not prevent me from progressing through the registrations.

**Comment by green-coder** [comment]
The problem is probably related to a regex which limits the number of characters for the extension of the domain name, it's not a whitelist.

**Comment by bago2k4** [comment]
Hey @green-coder thanks for the feedback. Yeah you are right the problem is in a regex the browser uses to automatically check the input values.
But we don't actually use those checks to limit submission of the data, only to suggest the user what the problem could be.
We are working now on fixing the problem, will ping you as son as we have it addressed.

**Comment by green-coder** [comment]
@bago2k4 If you don't mind, I would like to try to fix it and submit a PR.

**Comment by belucid** [comment]
@green-coder that'd be great! We'd love to get a PR from you on this. Would be helpful with our "other" discussion that's going on. 👍

**Comment by bago2k4** [comment]
Sure @green-coder , sorry for my intrusion but i didn't know about the other discussion. You can surely try to fix it.
